swagger: '2.0'
info:
  title: "Swagger CBE Anagrafica"
  version: "1.0.2"
basePath: "/anagrafica"
schemes:
  - https
  - http
paths:
  '/{codiceFiscale}':
    get:
      operationId: 'getPersonalInfo'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
      - name: codiceFiscale
        in: path
        required: true
        type: string
      - name: SessionID
        in: header
        required: true
        type: string
        description: 'Individua una sessione utente. Traccia tutte le operazioni dell utente durante la navigazione.'
      - name: Channel
        in: header
        required: true
        type: string
        description: 'Canale da cui parte la richiesta e che alcuni sistemi considerano per applicare logiche particolari.'
      - name: InteractionDate-Date
        in: header
        required: true
        type: string
        format: date
        description: 'Data interazione utente iniziale. Formato: yyyy-MM-dd'
      - name: InteractionDate-Time
        in: header
        required: true
        type: string
        format: time
        description: 'Orario interazione utente iniziale. Formato: HH:mm:ss.SSSZ'
      - name: BusinessID
        in: header
        required: true
        type: string
        description: 'Identificativo univoco di un processo di business (esempio di una ricarica). NOTA: valorizzato come il SID.'
      - name: TransactionID
        in: header
        required: true
        type: string
        description: 'Identificativo univoco della transazione.'
      - name: MessageID
        in: header
        required: true
        type: string
        description: 'Identificativo univoco del singolo messaggio inviato su un canale di comunicazione.'
      - name: Sourcesystem
        in: header
        required: true
        type: string
        description: 'identificativo del sistema chiamante (che origina la richiesta).'
      - name: DeviceType
        in: header
        required: false
        type: string
        description: 'Parametro solo per APP.  Indica il tipo di device da cui viene effettuata la richiesta.'
      - name: ClientVersion
        in: header
        required: false
        type: string
        description: 'Versione dell’app in uso'
      responses:
          200:
            description: "successful operation"
            schema:
              $ref: "#/definitions/resultGetPersonalInfo"
          400:
            description: "Controllo di validazione della richiesta fallito"
            schema:
              $ref: "#/definitions/errorManagement"
          500:
            description: "Errore generico: non è stato possibile portare a termine l’esecuzione del metodo."
            schema:
              $ref: "#/definitions/errorManagement"
 
definitions:
  resultGetPersonalInfo:
    properties:
       errorManagement:
          $ref: '#/definitions/errorManagement'
       personalInfo:
          $ref: '#/definitions/personalInfo'
  personalInfo:
    properties:
      referente:
        type: array
        items:
          $ref: '#/definitions/ReferenteDto'
  ReferenteDto:
    properties:
      progReferente:
        type: string
      tipoReferente:
        type: string
      tiid:
        type: string
      rifCliente:
        type: string
      flagMigrazione:
        type: string
      statoCertificazioneCliente:
        type: string
      nome:
        type: string
      cognome:
        type: string
      dataNascita:
        type: string
      comune:
        type: string
      comuneIstat:
        type: string
      comuneCatastale:
        type: string
      provincia:
        type: string
      provinciaIstat:
        type: string
      sesso:
        type: string
      titolo:
        type: string
      specializzazione:
        type: string
      documento:
        $ref: '#/definitions/DocumentoDto'
      contatti:
        $ref: '#/definitions/ContattoDto'
    title: ReferenteDto
  DocumentoDto:
    properties:
      tipoDocumento:
        type: string
      numeroDocumento:
        type: string
      rilasciatoDa:
        type: string
      dataRilascio:
        type: string
      dataScadenza:
        type: string
      provinciaRilascio:
        type: string
      provinciaRilascioIstat:
        type: string
      comuneRilascio:
        type: string
      comuneRilascioIstat:
        type: string
      comuneRilascioCatastale:
        type: string
    title: DocumentoDto
  ContattoDto:
    properties:
      indirizzoEmail:
        type: string
      altroIndirizzo:
        type: string
      recapitoTelefonicoNumero:
        type: string
      altroRecapitoNumero:
        type: string
      faxNumero:
        type: string
    title: ContattoDto
  errorManagement:
    properties:
      status:
        type: "string"
        example: "KO"
        description: "status della richiesta"
      errorCode:
        type: "string"
        description: "codice errore"
      errorMessage:
        type: "string"
        description: "descrizione errore"
    required:
      - status     
 